#pragma once

#include "Component.h"
#include "MeshComponents/StaticMesh.h"
#include "MeshComponents/InstanceMesh.h"
#include "CameraComponents/Camera.h"
#include "CameraComponents/FirstPersonController.h"
#include "MaterialComponents/Material.h"
#include "MaterialComponents/SimpleTexture.h"
#include "CollisionComponents/BoxCollider.h"
#include "CharacterComponents/CollectableComponent.h"
#include "CharacterComponents/Particle.h"
#include "CharacterComponents/ShardMovement.h"
#include "CharacterComponents/BeamComponent.h"
#include "CharacterComponents/ThirdPersonCharacterController.h"
#include "CameraComponents/ThirdPersonOrbitalController.h"
#include "MeshComponents/Terrain.h"
#include "MeshComponents/Grass.h"

#include "LevelEditor/LevelBuilder.h"
#include "LightComponents/PointLight.h"
#include "LightComponents/Light.h"
#include "LightComponents/DirLight.h"
#include "GUIComponents/GUI.h"
#include "GameStateComponents/GameState.h"