#pragma once
#define GL_VERTEX_POSITION_ATTRIBUTE 0
#define GL_VERTEX_NORMAL_ATTRIBUTE 1
#define GL_VERTEX_TEXTURE_ATTRIBUTE 2
#define GL_VERTEX_INSTANCE_MATRIX_ATTRIBUTE 3
#define GL_WRITE_BUFFER 0x0C03
#define GL_READ_WRITE_BUFFER 0x0C04
